# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BackgroundCustomConf.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BackgroundCustomConf(object):
    def setupUi(self, BackgroundCustomConf):
        BackgroundCustomConf.setObjectName("BackgroundCustomConf")
        BackgroundCustomConf.resize(758, 404)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(BackgroundCustomConf)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.colorGradientConf = QtWidgets.QWidget(BackgroundCustomConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorGradientConf.sizePolicy().hasHeightForWidth())
        self.colorGradientConf.setSizePolicy(sizePolicy)
        self.colorGradientConf.setObjectName("colorGradientConf")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.colorGradientConf)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.colorGradientChoice = QtWidgets.QWidget(self.colorGradientConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorGradientChoice.sizePolicy().hasHeightForWidth())
        self.colorGradientChoice.setSizePolicy(sizePolicy)
        self.colorGradientChoice.setObjectName("colorGradientChoice")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.colorGradientChoice)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.colorChoice = QtWidgets.QRadioButton(self.colorGradientChoice)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.colorChoice.setFont(font)
        self.colorChoice.setObjectName("colorChoice")
        self.horizontalLayout_4.addWidget(self.colorChoice)
        self.gradientChoice = QtWidgets.QRadioButton(self.colorGradientChoice)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.gradientChoice.setFont(font)
        self.gradientChoice.setObjectName("gradientChoice")
        self.horizontalLayout_4.addWidget(self.gradientChoice)
        self.verticalLayout_2.addWidget(self.colorGradientChoice)
        self.chosenCustomBackground = QtWidgets.QWidget(self.colorGradientConf)
        self.chosenCustomBackground.setObjectName("chosenCustomBackground")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.chosenCustomBackground)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chosenCustomBackgroundLayout = QtWidgets.QVBoxLayout()
        self.chosenCustomBackgroundLayout.setObjectName("chosenCustomBackgroundLayout")
        self.verticalLayout_4.addLayout(self.chosenCustomBackgroundLayout)
        self.verticalLayout_2.addWidget(self.chosenCustomBackground)
        self.verticalLayout_3.addWidget(self.colorGradientConf)
        self.customWidthHeightArea = QtWidgets.QWidget(BackgroundCustomConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customWidthHeightArea.sizePolicy().hasHeightForWidth())
        self.customWidthHeightArea.setSizePolicy(sizePolicy)
        self.customWidthHeightArea.setObjectName("customWidthHeightArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.customWidthHeightArea)
        self.verticalLayout.setObjectName("verticalLayout")
        self.customWidthArea = QtWidgets.QWidget(self.customWidthHeightArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customWidthArea.sizePolicy().hasHeightForWidth())
        self.customWidthArea.setSizePolicy(sizePolicy)
        self.customWidthArea.setObjectName("customWidthArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.customWidthArea)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCustomWidth = QtWidgets.QLabel(self.customWidthArea)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.labelCustomWidth.setFont(font)
        self.labelCustomWidth.setObjectName("labelCustomWidth")
        self.horizontalLayout_2.addWidget(self.labelCustomWidth)
        self.customWidthChoice = QtWidgets.QSpinBox(self.customWidthArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customWidthChoice.sizePolicy().hasHeightForWidth())
        self.customWidthChoice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.customWidthChoice.setFont(font)
        self.customWidthChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.customWidthChoice.setMinimum(1)
        self.customWidthChoice.setMaximum(10000)
        self.customWidthChoice.setObjectName("customWidthChoice")
        self.horizontalLayout_2.addWidget(self.customWidthChoice)
        self.labelPxWidth = QtWidgets.QLabel(self.customWidthArea)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.labelPxWidth.setFont(font)
        self.labelPxWidth.setObjectName("labelPxWidth")
        self.horizontalLayout_2.addWidget(self.labelPxWidth)
        self.verticalLayout.addWidget(self.customWidthArea)
        self.customHeightArea = QtWidgets.QWidget(self.customWidthHeightArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customHeightArea.sizePolicy().hasHeightForWidth())
        self.customHeightArea.setSizePolicy(sizePolicy)
        self.customHeightArea.setObjectName("customHeightArea")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.customHeightArea)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCustomHeight = QtWidgets.QLabel(self.customHeightArea)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.labelCustomHeight.setFont(font)
        self.labelCustomHeight.setObjectName("labelCustomHeight")
        self.horizontalLayout_3.addWidget(self.labelCustomHeight)
        self.customHeightChoice = QtWidgets.QSpinBox(self.customHeightArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customHeightChoice.sizePolicy().hasHeightForWidth())
        self.customHeightChoice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.customHeightChoice.setFont(font)
        self.customHeightChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.customHeightChoice.setMinimum(1)
        self.customHeightChoice.setMaximum(10000)
        self.customHeightChoice.setObjectName("customHeightChoice")
        self.horizontalLayout_3.addWidget(self.customHeightChoice)
        self.labelPxHeight = QtWidgets.QLabel(self.customHeightArea)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.labelPxHeight.setFont(font)
        self.labelPxHeight.setObjectName("labelPxHeight")
        self.horizontalLayout_3.addWidget(self.labelPxHeight)
        self.verticalLayout.addWidget(self.customHeightArea)
        self.labelWarningWH = QtWidgets.QLabel(self.customWidthHeightArea)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.labelWarningWH.setFont(font)
        self.labelWarningWH.setObjectName("labelWarningWH")
        self.verticalLayout.addWidget(self.labelWarningWH)
        self.verticalLayout_3.addWidget(self.customWidthHeightArea)

        self.retranslateUi(BackgroundCustomConf)
        QtCore.QMetaObject.connectSlotsByName(BackgroundCustomConf)

    def retranslateUi(self, BackgroundCustomConf):
        _translate = QtCore.QCoreApplication.translate
        BackgroundCustomConf.setWindowTitle(_translate("BackgroundCustomConf", "BackgroundCustomConf"))
        self.colorChoice.setText(_translate("BackgroundCustomConf", "Background Color"))
        self.gradientChoice.setText(_translate("BackgroundCustomConf", "Background Gradient"))
        self.labelCustomWidth.setText(_translate("BackgroundCustomConf", "Width :  "))
        self.labelPxWidth.setText(_translate("BackgroundCustomConf", "px"))
        self.labelCustomHeight.setText(_translate("BackgroundCustomConf", "Height :  "))
        self.labelPxHeight.setText(_translate("BackgroundCustomConf", "px"))
        self.labelWarningWH.setText(_translate("BackgroundCustomConf", "Small values of Width and Height are not recommended."))

