# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PhotoApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PhotoApp(object):
    def setupUi(self, PhotoApp):
        PhotoApp.setObjectName("PhotoApp")
        PhotoApp.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PhotoApp.sizePolicy().hasHeightForWidth())
        PhotoApp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        PhotoApp.setFont(font)
        self.centralwidget = QtWidgets.QWidget(PhotoApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlsTab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsTab.sizePolicy().hasHeightForWidth())
        self.controlsTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.controlsTab.setFont(font)
        self.controlsTab.setUsesScrollButtons(True)
        self.controlsTab.setObjectName("controlsTab")
        self.photoPane = QtWidgets.QWidget()
        self.photoPane.setAutoFillBackground(False)
        self.photoPane.setStyleSheet("")
        self.photoPane.setObjectName("photoPane")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.photoPane)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.folderSettingsArea = QtWidgets.QScrollArea(self.photoPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderSettingsArea.sizePolicy().hasHeightForWidth())
        self.folderSettingsArea.setSizePolicy(sizePolicy)
        self.folderSettingsArea.setFrameShape(QtWidgets.QFrame.Box)
        self.folderSettingsArea.setWidgetResizable(True)
        self.folderSettingsArea.setObjectName("folderSettingsArea")
        self.folderSettings = QtWidgets.QWidget()
        self.folderSettings.setGeometry(QtCore.QRect(0, 0, 856, 68))
        self.folderSettings.setObjectName("folderSettings")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.folderSettings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderLabel = QtWidgets.QLabel(self.folderSettings)
        self.folderLabel.setObjectName("folderLabel")
        self.horizontalLayout.addWidget(self.folderLabel)
        self.folderPath = QtWidgets.QLineEdit(self.folderSettings)
        self.folderPath.setText("")
        self.folderPath.setObjectName("folderPath")
        self.horizontalLayout.addWidget(self.folderPath)
        self.refreshButton = QtWidgets.QPushButton(self.folderSettings)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.folderSettingsArea.setWidget(self.folderSettings)
        self.verticalLayout_2.addWidget(self.folderSettingsArea)
        self.photoListArea = QtWidgets.QScrollArea(self.photoPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photoListArea.sizePolicy().hasHeightForWidth())
        self.photoListArea.setSizePolicy(sizePolicy)
        self.photoListArea.setFrameShape(QtWidgets.QFrame.Box)
        self.photoListArea.setWidgetResizable(True)
        self.photoListArea.setObjectName("photoListArea")
        self.photoListContainer = QtWidgets.QWidget()
        self.photoListContainer.setGeometry(QtCore.QRect(0, 0, 856, 374))
        self.photoListContainer.setObjectName("photoListContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.photoListContainer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.photoList = QtWidgets.QVBoxLayout()
        self.photoList.setObjectName("photoList")
        self.verticalLayout_6.addLayout(self.photoList)
        self.labelRefreshRelated = QtWidgets.QLabel(self.photoListContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRefreshRelated.sizePolicy().hasHeightForWidth())
        self.labelRefreshRelated.setSizePolicy(sizePolicy)
        self.labelRefreshRelated.setObjectName("labelRefreshRelated")
        self.verticalLayout_6.addWidget(self.labelRefreshRelated)
        self.photoListArea.setWidget(self.photoListContainer)
        self.verticalLayout_2.addWidget(self.photoListArea)
        self.controlsTab.addTab(self.photoPane, "")
        self.backgroundPane = QtWidgets.QWidget()
        self.backgroundPane.setStyleSheet("")
        self.backgroundPane.setObjectName("backgroundPane")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.backgroundPane)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.backgroundChoiceArea = QtWidgets.QScrollArea(self.backgroundPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundChoiceArea.sizePolicy().hasHeightForWidth())
        self.backgroundChoiceArea.setSizePolicy(sizePolicy)
        self.backgroundChoiceArea.setWidgetResizable(True)
        self.backgroundChoiceArea.setObjectName("backgroundChoiceArea")
        self.backgroundChoice = QtWidgets.QWidget()
        self.backgroundChoice.setGeometry(QtCore.QRect(0, 0, 858, 68))
        self.backgroundChoice.setObjectName("backgroundChoice")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.backgroundChoice)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageChoice = QtWidgets.QRadioButton(self.backgroundChoice)
        self.imageChoice.setObjectName("imageChoice")
        self.horizontalLayout_3.addWidget(self.imageChoice)
        self.customChoice = QtWidgets.QRadioButton(self.backgroundChoice)
        self.customChoice.setObjectName("customChoice")
        self.horizontalLayout_3.addWidget(self.customChoice)
        self.backgroundChoiceArea.setWidget(self.backgroundChoice)
        self.verticalLayout_5.addWidget(self.backgroundChoiceArea)
        self.chosenBackgroundArea = QtWidgets.QScrollArea(self.backgroundPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chosenBackgroundArea.sizePolicy().hasHeightForWidth())
        self.chosenBackgroundArea.setSizePolicy(sizePolicy)
        self.chosenBackgroundArea.setWidgetResizable(True)
        self.chosenBackgroundArea.setObjectName("chosenBackgroundArea")
        self.chosenBackground = QtWidgets.QWidget()
        self.chosenBackground.setGeometry(QtCore.QRect(0, 0, 858, 378))
        self.chosenBackground.setObjectName("chosenBackground")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.chosenBackground)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chosenBackgroundLayout = QtWidgets.QVBoxLayout()
        self.chosenBackgroundLayout.setObjectName("chosenBackgroundLayout")
        self.verticalLayout_8.addLayout(self.chosenBackgroundLayout)
        self.chosenBackgroundArea.setWidget(self.chosenBackground)
        self.verticalLayout_5.addWidget(self.chosenBackgroundArea)
        self.controlsTab.addTab(self.backgroundPane, "")
        self.advancedOptions = QtWidgets.QWidget()
        self.advancedOptions.setObjectName("advancedOptions")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.advancedOptions)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.advancedOptionsArea = QtWidgets.QScrollArea(self.advancedOptions)
        self.advancedOptionsArea.setWidgetResizable(True)
        self.advancedOptionsArea.setObjectName("advancedOptionsArea")
        self.advancedOptionsContent = QtWidgets.QWidget()
        self.advancedOptionsContent.setGeometry(QtCore.QRect(0, 0, 858, 454))
        self.advancedOptionsContent.setObjectName("advancedOptionsContent")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.advancedOptionsContent)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.executionTimeArea = QtWidgets.QWidget(self.advancedOptionsContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executionTimeArea.sizePolicy().hasHeightForWidth())
        self.executionTimeArea.setSizePolicy(sizePolicy)
        self.executionTimeArea.setObjectName("executionTimeArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.executionTimeArea)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.executionTimeLabel = QtWidgets.QLabel(self.executionTimeArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executionTimeLabel.sizePolicy().hasHeightForWidth())
        self.executionTimeLabel.setSizePolicy(sizePolicy)
        self.executionTimeLabel.setObjectName("executionTimeLabel")
        self.horizontalLayout_2.addWidget(self.executionTimeLabel)
        self.executionTimeValue = QtWidgets.QSpinBox(self.executionTimeArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executionTimeValue.sizePolicy().hasHeightForWidth())
        self.executionTimeValue.setSizePolicy(sizePolicy)
        self.executionTimeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.executionTimeValue.setMinimum(1)
        self.executionTimeValue.setMaximum(600)
        self.executionTimeValue.setProperty("value", 15)
        self.executionTimeValue.setObjectName("executionTimeValue")
        self.horizontalLayout_2.addWidget(self.executionTimeValue)
        self.executionTimeLabelSec = QtWidgets.QLabel(self.executionTimeArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executionTimeLabelSec.sizePolicy().hasHeightForWidth())
        self.executionTimeLabelSec.setSizePolicy(sizePolicy)
        self.executionTimeLabelSec.setObjectName("executionTimeLabelSec")
        self.horizontalLayout_2.addWidget(self.executionTimeLabelSec)
        self.verticalLayout_9.addWidget(self.executionTimeArea)
        self.warningOptions1 = QtWidgets.QLabel(self.advancedOptionsContent)
        self.warningOptions1.setObjectName("warningOptions1")
        self.verticalLayout_9.addWidget(self.warningOptions1)
        self.warningOptions2 = QtWidgets.QLabel(self.advancedOptionsContent)
        self.warningOptions2.setObjectName("warningOptions2")
        self.verticalLayout_9.addWidget(self.warningOptions2)
        self.advancedOptionsArea.setWidget(self.advancedOptionsContent)
        self.verticalLayout_7.addWidget(self.advancedOptionsArea)
        self.controlsTab.addTab(self.advancedOptions, "")
        self.verticalLayout.addWidget(self.controlsTab)
        self.makeCollageButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeCollageButton.setObjectName("makeCollageButton")
        self.verticalLayout.addWidget(self.makeCollageButton)
        PhotoApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PhotoApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        PhotoApp.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(PhotoApp)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        PhotoApp.setStatusBar(self.statusBar)

        self.retranslateUi(PhotoApp)
        self.controlsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PhotoApp)

    def retranslateUi(self, PhotoApp):
        _translate = QtCore.QCoreApplication.translate
        PhotoApp.setWindowTitle(_translate("PhotoApp", "PhotoGlue"))
        self.folderLabel.setText(_translate("PhotoApp", "Folder Path : "))
        self.refreshButton.setText(_translate("PhotoApp", "Refresh"))
        self.labelRefreshRelated.setText(_translate("PhotoApp", "After an eventual refresh, the selected photos will remain in the panel."))
        self.controlsTab.setTabText(self.controlsTab.indexOf(self.photoPane), _translate("PhotoApp", "Photos"))
        self.imageChoice.setText(_translate("PhotoApp", "Background Image"))
        self.customChoice.setText(_translate("PhotoApp", "Custom Background"))
        self.controlsTab.setTabText(self.controlsTab.indexOf(self.backgroundPane), _translate("PhotoApp", "Background"))
        self.executionTimeLabel.setText(_translate("PhotoApp", "Execution Time [min 1-max 600] :   "))
        self.executionTimeLabelSec.setText(_translate("PhotoApp", "s"))
        self.warningOptions1.setText(_translate("PhotoApp", "You can decide the execution time of the algorithm that gives you the collages."))
        self.warningOptions2.setText(_translate("PhotoApp", "Be careful to decide it: the greater the execution time, the better the collages will be."))
        self.controlsTab.setTabText(self.controlsTab.indexOf(self.advancedOptions), _translate("PhotoApp", "Advanced Options"))
        self.makeCollageButton.setText(_translate("PhotoApp", "Make Collages"))

